apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviereview-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: moviereview
  template:
    metadata:
      labels:
        app: moviereview
    spec:
      containers:
      - name: moviereview
        image: shivaji108/sample:kuberimg2
        ports:
        - containerPort: 5000
