apiVersion: apps/v1
kind: Deployment
metadata:
  name: symmetrical-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: symmetrical
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: symmetrical
        image: 22251a1257it258/symmetrical:kuberimg2
        ports:
        - containerPort: 5000
