
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: votingapp
  template:
    metadata:
      labels:
        app: votingapp
    spec:
      containers:
      - name: votingapp
        image: 22251a1257/devopsapp:kuberimg2
        ports:
        - containerPort: 5000

