apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops2-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops2
  template:
    metadata:
      labels:
        app: devops2
    spec:
      containers:
      - name: devops2
        image: 22251a1257it258/devops2:kuberimg3
        ports:
        - containerPort: 5000

