
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: 22251a1257/devopsapp:kuberimg2
        ports:
        - containerPort: 5000

