apiVersion: v1
kind: Service
metadata:
  name: devopsapp-service
spec:
  selector:
    app: devopsapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30084
  type: NodePort
