apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
spec:
  selector:
    app: votingapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081
  type: NodePort
